### ISSUE TITLE
什么时候开源代码

### ISSUE THREAD

**Issue by zq130320339** [flyinghu123/CPR#1]

**Comment by zq130320339** [comment]
你好 什么时候公布代码

**Comment by flyinghu123** [comment]
Thanks for your attention to our work! The code will be published after the paper is accepted.

**Comment by AIQuantScience** [comment]
> Thanks for your attention to our work! The code will be published after the paper is accepted.
兄弟，求尽快开源代码，想借用下思路做工业应用呀

**Comment by flyinghu123** [comment]
> > Thanks for your attention to our work! The code will be published after the paper is accepted.
> > 兄弟，求尽快开源代码，想借用下思路做工业应用呀

Thank you very much for your attention, you can easily re-implement the CPR algorithm based on our published paper. The paper is currently under review, and once the paper is accepted, we will release the official implementation.

**Comment by yeyeck** [comment]
any updates?

**Comment by flyinghu123** [comment]
> any updates?

At present, the paper is in the under review stage, and the code will be published after accepted.

**Comment by dianjingshilezhi** [comment]
any updates?

**Comment by flyinghu123** [comment]
> any updates?

At present, the paper is in the under review stage in peer review.

**Comment by flyinghu123** [comment]
> any updates?

At present, the paper is in peer review.

**Comment by weiliangwuw** [comment]
still in peer review?

**Comment by shining-love** [comment]
> still in peer review?

笑死哈哈哈

**Comment by flyinghu123** [comment]
> still in peer review?

Currently in the 'await AE decision' status.

**Comment by zq130320339** [comment]
还在评审吗

**Comment by d339293440** [comment]
How to use BoW to extract  sub-tensors' statistics

**Comment by flyinghu123** [comment]
> 还在评审吗

Yes.

**Comment by flyinghu123** [comment]
> How to use BoW to extract sub-tensors' statistics

![image](https://github.com/flyinghu123/CPR/assets/48802940/b0e12dcd-23bc-48cd-8478-6a346b1b62c3)

**Comment by d339293440** [comment]
请问该如何设置LRB structure 的output_channels

**Comment by zq130320339** [comment]
评审通过了吗

**Comment by yjszyd0813** [comment]
论文还没被录用吗？

**Comment by flyinghu123** [comment]
> 请问该如何设置LRB structure 的output_channels

Just change the output channels of the last layer of convolution

**Comment by flyinghu123** [comment]
> 论文还没被录用吗？

The paper is currently undergoing revisions.

**Comment by Kaze816** [comment]
long time to wait for

**Comment by shining-love** [comment]
> long time to wait for

I advise you to give up waiting！

**Comment by flyinghu123** [comment]
> > long time to wait for
> 
> I advise you to give up waiting！

![image](https://github.com/flyinghu123/CPR/assets/48802940/87ac635d-55f6-4305-af63-10f7aa70ee04)

I'm waiting, too.

**Comment by Kaze816** [comment]
> > long time to wait for
> 
> I advise you to give up waiting！

Maybe,  you are right.

**Comment by afvca** [comment]
Hello!

Congrats on your work, it shows very promising results. Looking forward to reading the codebase.

Just a question, when you open-source the code, could you also share the TensorRT models?

**Comment by GuoRunTang** [comment]
Looking forward to your codebase!

**Comment by Snailgoo** [comment]
Any updates?

Looking forward to your good news！

**Comment by gitfri021** [comment]
hi, 
really good work. 
Is there any update on the training code? when will it be released?
what is the status of the paper?

**Comment by DSluge** [comment]
作者您好，训练代码可以发我一份吗？2292966108@qq.com，期待您的回信！

**Comment by billhyde** [comment]
great work! thank you for sharing~
