### ISSUE TITLE
Seems Eq. (12) in the paper has something wrong.

### ISSUE THREAD

**Issue by hurri2000** [flyinghu123/CPR#3]
![Capture](https://github.com/flyinghu123/CPR/assets/33280706/34ecae3d-d682-4090-9226-5794cb229d79)
I think it should be :   ... yi *max(0, dist_p - m+) + (1-yi)*max(0,m-  - dist_n), in this way, the dist_p gets smaller and dist_n gets greater. please check.

Thanks for your great working.

Best regards,

**Comment by flyinghu123** [comment]
> ![Capture](https://user-images.githubusercontent.com/33280706/282720004-34ecae3d-d682-4090-9226-5794cb229d79.PNG) I think it should be : ... yi *max(0, dist_p - m+) + (1-yi)*max(0,m- - dist_n), in this way, the dist_p gets smaller and dist_n gets greater. please check.
> 
> Thanks for your great working.
> 
> Best regards,

The inner product is cosin similarity, so it is max(m+- dist_ p)

**Comment by hurri2000** [comment]
I see, thanks.
