### ISSUE TITLE
Inference Speed Measurement

### ISSUE THREAD

**Issue by Nothingtolose9979** [flyinghu123/CPR#4]
I have a question regarding the testing of inference speed. Are the reported inference speeds for each compared method based on the default batch size? Is the reported speed of CPR, CPR-fast, and CPR-faster calculated using a batch size of 32?

**Comment by flyinghu123** [comment]
For all the experiments about inference speed, batch size was set to 1.

**Comment by Nothingtolose9979** [comment]
Thank you!!!
