### ISSUE TITLE
考虑测一下MVTec LOCO AD数据集吗？感觉你的算法很适合

### ISSUE THREAD

**Issue by ControllableGeneration** [flyinghu123/CPR#5]
考虑测一下MVTec LOCO AD数据集吗？感觉你的算法很适合位置异常、还有像素级准确度

**Comment by flyinghu123** [comment]
> 考虑测一下MVTec LOCO AD数据集吗？感觉你的算法很适合位置异常、还有像素级准确度

I'll take it into consideration for future experiment.  Thanks for the recommendation!
