### ISSUE TITLE
Have you ever tested the inference speed of large images? (>256)

### ISSUE THREAD

**Issue by yjszyd0813** [flyinghu123/CPR#6]
I have read your paper and feel it is very good. I am more concerned about reasoning speed. Have you ever tested the inference speed of larger image sizes? (512 * 512, 1024 * 1024)
<img width="393" alt="image" src="https://github.com/flyinghu123/CPR/assets/80048995/01279ead-c9c2-4160-bfb8-6f5959f1f174">

**Comment by flyinghu123** [comment]
> I have read your paper and feel it is very good. I am more concerned about reasoning speed. Have you ever tested the inference speed of larger image sizes? (512 * 512, 1024 * 1024) <img alt="image" width="393" src="https://private-user-images.githubusercontent.com/80048995/306116913-01279ead-c9c2-4160-bfb8-6f5959f1f174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTQ5MDYsIm5iZiI6MTcwODQxNDYwNiwicGF0aCI6Ii84MDA0ODk5NS8zMDYxMTY5MTMtMDEyNzllYWQtYzljMi00MTYwLWJmYjgtNmY1OTU5ZjFmMTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA3MzY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNWNkZjUyNTVmNDlhNWE4MTI2YjkwNGRjYWIzYjQ0MWJmNGFmOWU4M2ZkNTI3OTBmOGRjNDYwY2NmOWI0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1EMYyyMVo05sUVBB_HKn0-HXyneffFQiB9d9B7UkxE4">

Thank you for your positive feedback on our paper.  I'm glad to hear that you found it valuable.  Regarding your question about testing larger image sizes for inference speed, currently, our experiments have been conducted on images with a size of 320.  We haven't explored sizes larger than 320 yet.  As our approach relies on storing reference sets in GPU memory for acceleration, testing larger sizes would depend on having sufficient GPU memory resources.  We will certainly consider experimenting with larger image sizes in the future.
