### ISSUE TITLE
No code?

### ISSUE THREAD

**Issue by Qu3tzal** [flyinghu123/CPR#7]
Hello!

It's been more than 6 months since the paper got released but we still don't have access to the source.

What's blocking the publication of the source code?
Did you find errors/issues that compromise the results you published?

**Comment by flyinghu123** [comment]
> Hello!
> 
> It's been more than 6 months since the paper got released but we still don't have access to the source.
> 
> What's blocking the publication of the source code? Did you find errors/issues that compromise the results you published?

Thank you for your interest in the paper.
The paper is currently undergoing revisions.
I didn't find any issues compromising the results we published.
I will release the code as soon as the results of the paper come out.
You can attempt to reproducing the paper. 
#1

**Comment by Qu3tzal** [comment]
I have trouble reproducing the diffusion model. How important is the coordinates map for the generation process?
Do you use a position encoding or normalized coordinates or rough integer coordinates in this map?

**Comment by flyinghu123** [comment]
> I have trouble reproducing the diffusion model. How important is the coordinates map for the generation process? Do you use a position encoding or normalized coordinates or rough integer coordinates in this map?

Are you referring to the sampling point process? The paper employs normalization within the range [-1, 1] and subsequently uses PyTorch's grid_sample function for interpolation. Alternatively, you could directly use integers and fetch features through index operations to proceed with the subsequent loss calculation.

**Comment by Qu3tzal** [comment]
No sorry, I was working on multiple things at the same time and got confused/mixed up, that question was not for your paper. 🙇

**Comment by Qu3tzal** [comment]
I'll wait on #1 to be resolved to get the source code.
