### ISSUE TITLE
When will the training code be available?

### ISSUE THREAD

**Issue by rumozam** [flyinghu123/CPR#8]
Hi there!
Thank you for your work and congrats on the great results!
I know everyone hates this question, but we would like to evaluate your work to cite it in our paper, so could you give a hint how long the publication of the training code will still take? :D
Thank you!

**Comment by flyinghu123** [comment]
> Hi there! Thank you for your work and congrats on the great results! I know everyone hates this question, but we would like to evaluate your work to cite it in our paper, so could you give a hint how long the publication of the training code will still take? :D Thank you!

Now I have submitted the revision, and I will release the train code as soon as possible after the review.

**Comment by LukaHenig** [comment]
Hi there!
Any news or updates about the revision?

**Comment by gitfri021** [comment]
+1

**Comment by IceIce1ce** [comment]
+1

**Comment by briliantnugraha** [comment]
Hi @flyinghu123, thanks for the great paper!
Btw, could we know, will there be a released training code in the near future? thank you~

**Comment by 2519756632** [comment]
Hi there!
Thank you for your work and congrats on the great results!
I know everyone hates this question, but we would like to evaluate your work to cite it in our paper, so could you give a hint how long the publication of the training code will still take? 
Thank you!
